// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Color is an autogenerated mock type for the Color type
type Color struct {
	mock.Mock
}

// Printf provides a mock function with given fields: format, a
func (_m *Color) Printf(format string, a ...interface{}) (int, error) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, a...)
	ret := _m.Called(_ca...)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, ...interface{}) int); ok {
		r0 = rf(format, a...)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(format, a...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Println provides a mock function with given fields: a
func (_m *Color) Println(a ...interface{}) (int, error) {
	var _ca []interface{}
	_ca = append(_ca, a...)
	ret := _m.Called(_ca...)

	var r0 int
	if rf, ok := ret.Get(0).(func(...interface{}) int); ok {
		r0 = rf(a...)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(...interface{}) error); ok {
		r1 = rf(a...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
