// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// NumverifySupplier is an autogenerated mock type for the NumverifySupplierInterface type
type NumverifySupplier struct {
	mock.Mock
}

// Request provides a mock function with given fields:
func (_m *NumverifySupplier) Request() suppliers.NumverifySupplierRequestInterface {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 suppliers.NumverifySupplierRequestInterface
	if rf, ok := ret.Get(0).(func() suppliers.NumverifySupplierRequestInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(suppliers.NumverifySupplierRequestInterface)
		}
	}

	return r0
}

// NewNumverifySupplier creates a new instance of NumverifySupplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNumverifySupplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *NumverifySupplier {
	mock := &NumverifySupplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
