// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// NumverifySupplierReq is an autogenerated mock type for the NumverifySupplierRequestInterface type
type NumverifySupplierReq struct {
	mock.Mock
}

// SetApiKey provides a mock function with given fields: _a0
func (_m *NumverifySupplierReq) SetApiKey(_a0 string) suppliers.NumverifySupplierRequestInterface {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetApiKey")
	}

	var r0 suppliers.NumverifySupplierRequestInterface
	if rf, ok := ret.Get(0).(func(string) suppliers.NumverifySupplierRequestInterface); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(suppliers.NumverifySupplierRequestInterface)
		}
	}

	return r0
}

// ValidateNumber provides a mock function with given fields: _a0
func (_m *NumverifySupplierReq) ValidateNumber(_a0 string) (*suppliers.NumverifyValidateResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ValidateNumber")
	}

	var r0 *suppliers.NumverifyValidateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*suppliers.NumverifyValidateResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *suppliers.NumverifyValidateResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.NumverifyValidateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNumverifySupplierReq creates a new instance of NumverifySupplierReq. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNumverifySupplierReq(t interface {
	mock.TestingT
	Cleanup(func())
}) *NumverifySupplierReq {
	mock := &NumverifySupplierReq{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
