// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// NumverifySupplier is an autogenerated mock type for the NumverifySupplierInterface type
type NumverifySupplier struct {
	mock.Mock
}

// IsAvailable provides a mock function with given fields:
func (_m *NumverifySupplier) IsAvailable() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Validate provides a mock function with given fields: _a0
func (_m *NumverifySupplier) Validate(_a0 string) (*suppliers.NumverifyValidateResponse, error) {
	ret := _m.Called(_a0)

	var r0 *suppliers.NumverifyValidateResponse
	if rf, ok := ret.Get(0).(func(string) *suppliers.NumverifyValidateResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.NumverifyValidateResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
