// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	number "github.com/sundowndev/phoneinfoga/v2/lib/number"
	suppliers "github.com/sundowndev/phoneinfoga/v2/lib/remote/suppliers"
)

// OVHSupplier is an autogenerated mock type for the OVHSupplierInterface type
type OVHSupplier struct {
	mock.Mock
}

// Search provides a mock function with given fields: _a0
func (_m *OVHSupplier) Search(_a0 number.Number) (*suppliers.OVHScannerResponse, error) {
	ret := _m.Called(_a0)

	var r0 *suppliers.OVHScannerResponse
	if rf, ok := ret.Get(0).(func(number.Number) *suppliers.OVHScannerResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*suppliers.OVHScannerResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(number.Number) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
