// Code generated by mockery v2.8.0. DO NOT EDIT.

package mocks

import (
	plugin "plugin"

	mock "github.com/stretchr/testify/mock"
)

// Plugin is an autogenerated mock type for the Plugin type
type Plugin struct {
	mock.Mock
}

// Lookup provides a mock function with given fields: _a0
func (_m *Plugin) Lookup(_a0 string) (plugin.Symbol, error) {
	ret := _m.Called(_a0)

	var r0 plugin.Symbol
	if rf, ok := ret.Get(0).(func(string) plugin.Symbol); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.Symbol)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
